import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/NextThemeProvider";
import { QueryProvider } from "@/components/providers/QueryProvider";
import { ModalProider } from "@/components/providers/ModalProvider";
import { LeftSide } from "@/components/left-side/LeftSide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          storageKey="whatsapp-theme"
        >
          <QueryProvider>
            <ModalProider />
            {children}
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
